### ISSUE TITLE
Icons remain black after hovering

### ISSUE THREAD

**Issue by Swiftstalion214** [uiriansan/SilentSDDM#21]
**Describe the bug**
I'm using rei config. After hovering on the icons, they highlight and change color(expected behavior) but after I move mouse away they keep their color. If repeated multiple times, they get darker and darker
**To Reproduce**
Idk, I just installed it(first tried aur package, then git command) and it was like that since beginning

**Expected behavior**
Icons returning to their original colors after I move the mouse away (even in the showcase video of this config they return to normal)

**Screenshots/Videos**

https://github.com/user-attachments/assets/414a4759-87d6-49cd-919e-2cbed8144f9f

**Comment by its-mrarsikk** [comment]
Hello! Please provide the output of the following command:
`sudo journalctl -u sddm -e --no-pager`

**Comment by Swiftstalion214** [comment]
Wait, sorry. I just did the actual reboot and they still become black

**Comment by Swiftstalion214** [comment]
I ./install.shed and yep, they keep color, just get more pixelated

**Comment by uiriansan** [comment]
I pushed two new commits into 'color-overlay'. Hopefully they will fix the pixelation.

**Comment by Swiftstalion214** [comment]
I'm not sure how to update, so I just deleted the SilentSDDM and used the same git clone command you sent before. The issue still remains

**Comment by uiriansan** [comment]
Fucking hell, I hate QML

**Comment by uiriansan** [comment]
Okay, what about now?

```bash
cd SilentSDDM/
git checkout color-overlay
git pull origin color-overlay
./test.sh
```

**Comment by its-mrarsikk** [comment]
@uiriansan I could package the coloroverlay branch to the AUR if that's the fix...

**Comment by uiriansan** [comment]
@its-mrarsikk, probably not the fix. I just figured something out.

**Comment by Swiftstalion214** [comment]
Sorry, I just noticed but  some icons still remain black

https://github.com/user-attachments/assets/050c9148-7c48-4cc5-98ba-943512655009

**Comment by Swiftstalion214** [comment]
I'm not sure if you're gonna see the message after it's closed, so I'll @uiriansan just in case

**Comment by uiriansan** [comment]
> Sorry, I just noticed but some icons still remain black
> recording_2025-06-26_07.29.54.mp4

Those should be fixed in the `main` branch now. Please, update it again and check if every single icon is correctly colored, including the ones in the virtual keyboard.

```bash
cd SilentSDDM/
git checkout main
git pull origin main
./test.sh
'''

**Comment by uiriansan** [comment]
Yes

**Comment by uiriansan** [comment]
It's bed time for me. I'll take a look tomorrow.

**Comment by Swiftstalion214** [comment]
No problem

**Comment by Swiftstalion214** [comment]
Done some testing. Everything seems fine in other sections, but on the keyboard there's some weird behavior. The language, shift, keyboard, backspace and enter have some white behind them in actual booting (in test.sh they just look slightly off). In boot, spamming &123 key forces the all icons(in test.sh only keyboard icon) to get darker, I assume they get overlapped with the other icons (also adds icon to the to the spinner, might be only test.sh, but I'm not sure. It just logins me in so fast I can't really see)

![Image](https://github.com/user-attachments/assets/c1dc51a6-4c76-4872-b4aa-28ba70f0cd3a)

![Image](https://github.com/user-attachments/assets/ae11fffb-e021-4f64-b434-19f34751a1c1)

![Image](https://github.com/user-attachments/assets/a004b819-99f4-4d10-a286-e38dd4770433)

https://github.com/user-attachments/assets/32bbdac6-4d41-4d4e-bcd2-57b36a8d0fed

![Image](https://github.com/user-attachments/assets/50eba961-8898-422c-9705-a1615591dbaf)

https://github.com/user-attachments/assets/ab66588b-c597-49c7-9f91-bfd3949f7051

**Comment by uiriansan** [comment]
If you update `main` again most of these should be fixed (I hope). I'm not sure about that bug with the hide button in the keyboard overlapping, tho. If it's not fixed, I have no idea what is causing it.

**Comment by Swiftstalion214** [comment]
Everything seems fine so far. I'm gonna mess a bit more and if nothing comes up I'll close the issue
