### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by vannyx404x** [uiriansan/SilentSDDM#43]
Why always freeze(just One Animation)

**Comment by vannyx404x** [comment]
https://github.com/user-attachments/assets/3a088aea-f4f8-4fe7-9bd4-df06b8ad34fd
Freezeee!

**Comment by uiriansan** [comment]
> Why does it freezes when I login even my password is correct, It was working a couple of days ago but now it freezes.

Man, "freeze" can mean so many things...

What exactly is happening? This can be caused by the changes I've committed yesterday or by your DE/WM crashing. There's no way for me to know with that little information.

**Comment by cosmoDiv** [comment]
I think hyprland(uwsm) is the problem even I reinstalled arch it still freezes

**Comment by cosmoDiv** [comment]
@uiriansan  I found out earlier it was just a bug to the new version of uswm 🤦‍♂️

**Comment by uiriansan** [comment]
@vannyx404x, run these commands and show me the results:

1. 
```bash
cat /etc/sddm.conf
```
2. 
```bash
journalctl -u sddm -e --no-pager
```

**Comment by uiriansan** [comment]
I am closing this. The problem is likely related to the multimedia backend and your GPU drivers:

https://github.com/uiriansan/SilentSDDM/issues/42#issuecomment-3169577578
